apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: securekubeops-monitor
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: securekubeops
  endpoints:
  - port: http
    path: /metrics
    interval: 15s