name: SecureKubeOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Build Docker image
    - name: Build Docker Image
      run: docker build -t securekubeops-app .

    # 3. Scan Image with Trivy
    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: securekubeops-app
        format: table
        exit-code: 0
        severity: HIGH,CRITICAL


    # 5. Deploy (simulated for now)
    - name: Deployment Step
      run: echo "Deploying to Kubernetes..."