name: SecureKubeOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:

    # 1. Checkout code
    - name: Checkout Code
      uses: actions/checkout@v3

    # 2. Build Docker image
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/securekubeops .

    - name: Push Docker Image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/securekubeops

    # 3. Scan Image with Trivy
    - name: Scan Image with Trivy
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ secrets.DOCKER_USERNAME }}/securekubeops:latest
        format: table
        exit-code: 0
        severity: HIGH,CRITICAL


    # 5. Deploy (simulated for now)
    - name: Deployment Step
      run: echo "Deploying to Kubernetes..."

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
